### PR TITLE
adding ntlm support

### PR DESCRIPTION
**Pull request by chriscate**
tested this with python 2.7.9 and was able to successfully connect to our NTLM Authenticated SharePoint server

### CODE REVIEW

**Comment by cgc17** [comment]
usage:
opener = ntlm_auth_opener(server_url, 'domain\\user', 'password')

**Comment by alexsdutton** [comment]
Cool, thanks! Can you add a short something about this to the README? Once that's done, I'll be happy to merge.

**Comment by cgc17** [comment]
@alexsdutton No problem.  I added some short notes in the README for ntlm auth.

**Comment by cgc17** [comment]
Hey @alexsdutton, just wanted to check and see if there is anything else you need me to do before this can be merged.

**Comment by cgc17** [comment]
I just wanted to make a note that I did not add ntlm to cmd.py as we are not using the command line tool, so it actually didn't even register in my mind.  This would be adding ntlm support for scripting capability, but not for the command line tool.  I'll look at getting it added for that as well.

**Comment by alexsdutton** [comment]
In retrospect, we should just have one opener that can handle both Basic and NTLM without having to specify which should be used. If we rename `basic_auth_opener` to e.g. `passworded_opener`, add a wrapper so the old name still works, and then add both Basic and NTLM handlers to the opener we create.

**Comment by cgc17** [comment]
Agreed, that would be better. I'll work on this.

**Comment by cgc17** [comment]
this got closed when I reset my fork... just re-opening. nothing new yet, but will work on having authentication be auto-selected to basic or ntlm

**Comment by cgc17** [comment]
does anyone know if/how you can access the HTTP headers prior to authenticating? I'm trying to avoid having to first try basic auth, then if it fails try ntlm, but that may be what we need to do.

**Comment by pagey101** [comment]
hey, when's the new release with ntlm??

**Comment by cgc17** [comment]
@pagey101 thanks for following up. I haven't had much time to work on generalizing the ntlm solution yet because of work/travel. I hope to get to it soon, but we'll see.

In the meantime, if you'd like ntlm and don't mind explicitly calling the alternate auth function, you can copy the files from https://github.com/cgc17/python-sharepoint/tree/master. 

There's a little blurb in the readme about how to use it.

**Comment by pagey101** [comment]
Thanks much!

I've modified the files but not able to import the new module.. am i missing something?

:)

Matt

**Comment by pagey101** [comment]
Ignore that.. this is awesome..

**Comment by avlsi** [comment]
Hi,

Is there a way to use this ntlm_auth_opener(server_url, 'domain\user', 'password')
 with from requests_ntlm import HttpNtlmAuth, HttpNtlmSspiAuth

HttpNtlmSspiAuth() can help in directly using default windows username and password.

**Comment by chriscate** [comment]
@alexsdutton needed this for another project, so went ahead and made a change to have a single opener with a wrapper to the old `basic_auth_opener` as well as `ntlm_auth_opener`

**Comment by chriscate** [comment]
I also just took a stab at adding ntlm to `cmd` as an option for completeness.  I don't use `cmd` so haven't tested this piece, but wanted to give a starting point for someone else to look over.  Or, I can remove it - whichever is preferred.

**Comment by chriscate** [comment]
hold on this... seems to be issues with the underlying ntlm3 lib either b/c I'm on python 3.6 now or... ? I'll have to see.

**Comment by chriscate** [comment]
@alexsdutton okay, the error I was getting was caused by being on python 3.6.  Tested (with exception of `cmd` as I don't use it) and this works on python 2.7.14.

**Pull request closed without merging**
